/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserComplaintsRouteImport } from './routes/user-complaints'
import { Route as KiloinRouteImport } from './routes/kiloin'
import { Route as InewsByteRouteImport } from './routes/inews-byte'
import { Route as GraphicsDesignRouteImport } from './routes/graphics-design'
import { Route as FarmagymRouteImport } from './routes/farmagym'
import { Route as ClientWebsitesRouteImport } from './routes/client-websites'
import { Route as AmrFarmsRouteImport } from './routes/amr-farms'
import { Route as AgriplantRouteImport } from './routes/agriplant'
import { Route as IndexRouteImport } from './routes/index'

const UserComplaintsRoute = UserComplaintsRouteImport.update({
  id: '/user-complaints',
  path: '/user-complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const KiloinRoute = KiloinRouteImport.update({
  id: '/kiloin',
  path: '/kiloin',
  getParentRoute: () => rootRouteImport,
} as any)
const InewsByteRoute = InewsByteRouteImport.update({
  id: '/inews-byte',
  path: '/inews-byte',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsDesignRoute = GraphicsDesignRouteImport.update({
  id: '/graphics-design',
  path: '/graphics-design',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmagymRoute = FarmagymRouteImport.update({
  id: '/farmagym',
  path: '/farmagym',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientWebsitesRoute = ClientWebsitesRouteImport.update({
  id: '/client-websites',
  path: '/client-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const AmrFarmsRoute = AmrFarmsRouteImport.update({
  id: '/amr-farms',
  path: '/amr-farms',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriplantRoute = AgriplantRouteImport.update({
  id: '/agriplant',
  path: '/agriplant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agriplant': typeof AgriplantRoute
  '/amr-farms': typeof AmrFarmsRoute
  '/client-websites': typeof ClientWebsitesRoute
  '/farmagym': typeof FarmagymRoute
  '/graphics-design': typeof GraphicsDesignRoute
  '/inews-byte': typeof InewsByteRoute
  '/kiloin': typeof KiloinRoute
  '/user-complaints': typeof UserComplaintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agriplant': typeof AgriplantRoute
  '/amr-farms': typeof AmrFarmsRoute
  '/client-websites': typeof ClientWebsitesRoute
  '/farmagym': typeof FarmagymRoute
  '/graphics-design': typeof GraphicsDesignRoute
  '/inews-byte': typeof InewsByteRoute
  '/kiloin': typeof KiloinRoute
  '/user-complaints': typeof UserComplaintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agriplant': typeof AgriplantRoute
  '/amr-farms': typeof AmrFarmsRoute
  '/client-websites': typeof ClientWebsitesRoute
  '/farmagym': typeof FarmagymRoute
  '/graphics-design': typeof GraphicsDesignRoute
  '/inews-byte': typeof InewsByteRoute
  '/kiloin': typeof KiloinRoute
  '/user-complaints': typeof UserComplaintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agriplant'
    | '/amr-farms'
    | '/client-websites'
    | '/farmagym'
    | '/graphics-design'
    | '/inews-byte'
    | '/kiloin'
    | '/user-complaints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agriplant'
    | '/amr-farms'
    | '/client-websites'
    | '/farmagym'
    | '/graphics-design'
    | '/inews-byte'
    | '/kiloin'
    | '/user-complaints'
  id:
    | '__root__'
    | '/'
    | '/agriplant'
    | '/amr-farms'
    | '/client-websites'
    | '/farmagym'
    | '/graphics-design'
    | '/inews-byte'
    | '/kiloin'
    | '/user-complaints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgriplantRoute: typeof AgriplantRoute
  AmrFarmsRoute: typeof AmrFarmsRoute
  ClientWebsitesRoute: typeof ClientWebsitesRoute
  FarmagymRoute: typeof FarmagymRoute
  GraphicsDesignRoute: typeof GraphicsDesignRoute
  InewsByteRoute: typeof InewsByteRoute
  KiloinRoute: typeof KiloinRoute
  UserComplaintsRoute: typeof UserComplaintsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-complaints': {
      id: '/user-complaints'
      path: '/user-complaints'
      fullPath: '/user-complaints'
      preLoaderRoute: typeof UserComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiloin': {
      id: '/kiloin'
      path: '/kiloin'
      fullPath: '/kiloin'
      preLoaderRoute: typeof KiloinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inews-byte': {
      id: '/inews-byte'
      path: '/inews-byte'
      fullPath: '/inews-byte'
      preLoaderRoute: typeof InewsByteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics-design': {
      id: '/graphics-design'
      path: '/graphics-design'
      fullPath: '/graphics-design'
      preLoaderRoute: typeof GraphicsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmagym': {
      id: '/farmagym'
      path: '/farmagym'
      fullPath: '/farmagym'
      preLoaderRoute: typeof FarmagymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-websites': {
      id: '/client-websites'
      path: '/client-websites'
      fullPath: '/client-websites'
      preLoaderRoute: typeof ClientWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amr-farms': {
      id: '/amr-farms'
      path: '/amr-farms'
      fullPath: '/amr-farms'
      preLoaderRoute: typeof AmrFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriplant': {
      id: '/agriplant'
      path: '/agriplant'
      fullPath: '/agriplant'
      preLoaderRoute: typeof AgriplantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgriplantRoute: AgriplantRoute,
  AmrFarmsRoute: AmrFarmsRoute,
  ClientWebsitesRoute: ClientWebsitesRoute,
  FarmagymRoute: FarmagymRoute,
  GraphicsDesignRoute: GraphicsDesignRoute,
  InewsByteRoute: InewsByteRoute,
  KiloinRoute: KiloinRoute,
  UserComplaintsRoute: UserComplaintsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
